version: "3"
services:
  app:
    build: ./
    command: /bin/bash -c "./zinobe/vendor/bin/phinx migrate -c /zinobe/phinx.yml; php -S 0.0.0.0:8080 /zinobe/public/index.php"
    ports:
      - "8080:8080"
    volumes:
      - ./:/zinobe
    env_file:
      - .env

  mariadb:
    image: mariadb
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: user_directory
